config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root to: "pages#home"
  get '/about', to: 'pages#about'
  get '/education', to: 'pages#education'
  get '/skills', to: 'pages#skills'
  get '/portfolio', to: 'pages#portfolio'
  get '/contact/new', to: 'contact#new'
  post '/contact', to: 'contact#create', as: 'contact_index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: 'Thank you for contacting us!'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def education
  end

  def skills
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div id="index">
  <h3>Melbourne/Remote</h3>
  <h3>English/French</h3>

  <h2>About me</h2>
  <div class="photo-description">
    <%= image_tag "me.jpg", class: "me" %>
      <div class="bio">
        <p>Hello world! I’m a french full-stack developer based in Melbourne.
        <br>
        After working for 3 years as a social worker, mainly with asylum seekers and refugees I left France to travel in Australia. The country closed its borders on month after my arrival and I stayed there for 3 years working as a tractor operator and traveling around in my van.
        One day, I was listening to a podcast about a guy who learned how to code doing a coding bootcamp with Le Wagon. Something clicked in me and I new immediately I wanted to do the same thing.
        <br>
        The bootcamp was an amazing experience and I immediately enjoyed coding. I love creating the aesthetic of a website but also working on the logic of the back-end. I graduate arch 2023 from Le Wagon Bali and I am now looking for my first job as a developer.  I am a highly motivated and adaptable individual
      </div>
  </div>
      <div class="button-download-shadow">
        <%= link_to "Download My Resume", "/resume.pdf", download: "My_Resume.pdf", class: "button-download" %>
      </div>
</div>

app/views/contact/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contact/new.html.erb
<div id="new">
  <h2>Contact</h2>
  <div class="form-container">
  <%= form_with url: contact_index_path, method: :post do |form| %>
    <div>
      <%= form.text_field :name, placeholder: 'Your name', label:false %>
    </div>
    <div>
      <%= form.email_field :email, placeholder: 'Your email adress', label:false %>
    </div>
    <div>
      <%= form.text_area :message, placeholder: 'Your message', label:false %>
    </div>
    <div class="button-shadow-submit">
      <%= form.submit "Send" %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PORTFOLIO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <div class="container">
      <br>
      <% flash.each do |key, message| %>
      <p class="alert alert-<%= key %>"><%= message %></p>
      <% end %>
    </div>
    <% if current_page?(root_path) %>
      <%= yield %>
    <% else %>
    <nav class="navbar">
      <h1 class="name">Fanny</h1>
      <a href="/about"><h2>About me</h2></a>
      <a href="/education"><h2>Education</h2></a>
      <a href="/skills"><h2 class="skill-navbar">Skills</h2></a>
      <a href="/portfolio"><h2 class="skill-portfolio">Portfolio</h2></a>
      <div class="button-shadow-contact">
        <a href="/contact/new"><button type="button" href="/contact/new" class="button-contact">Contact me</button></a>
      </div>
    </nav>
    <%= yield %>
  <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">

  <div class="logo-location">
    <%= image_tag "happy-location.png", class: "happy-location" %>
    <h3><i class="fa-regular fa-location-smile"></i>Melbourne/France/Remote</h3>
  </div>
  <div class="logo-language">
    <%= image_tag "robot.png", class: "robot" %>
    <h3>English/French</h3>
  </div>

  <h2>About me</h2>
  <div class="photo-description">
    <%= image_tag "me.jpg", class: "me" %>
      <div class="bio">
        <p>Hello world! I’m a french full-stack developer based in Melbourne.
        <br>
        After working for 3 years as a social worker, mainly with asylum seekers and refugees I left France to travel in Australia. The country closed its borders on month after my arrival and I stayed there for 3 years working as a tractor operator and traveling around in my van.
        One day, I was listening to a podcast about a guy who learned how to code doing a coding bootcamp with Le Wagon. Something clicked in me and I new immediately I wanted to do the same thing.
        <br>
        The bootcamp was an amazing experience and I immediately enjoyed coding. I love creating the aesthetic of a website but also working on the logic of the back-end. I graduate arch 2023 from Le Wagon Bali and I am now looking for my first job as a developer.  I am a highly motivated and adaptable individual
      </div>
  </div>
      <div class="button-download-shadow">
        <%= link_to "Download My Resume", "/resume.pdf", download: "My_Resume.pdf", class: "button-download" %>
      </div>
   <div class="icons-index">
    <a href="mailto:fanny.jousset@gmail.com"><i class="fa-sharp fa-regular fa-envelope"></i></a>
    <a href="https://github.com/FnnyJsst"><i class="fa-brands fa-github-alt"></i></a>
    <a href="https://www.linkedin.com/in/fanny-jousset/"><i class="fa-brands fa-linkedin"></i></a>
    <a href="https://www.instagram.com/fnnyjsst/?hl=fr"><i class="fa-brands fa-instagram"></i></a>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="contact">
  <h2>Contact</h2>
</div>

app/views/pages/education.html.erb
<div id="education">
  <div class="titles">
    <h2 class="education-title">Education</h2>
    <h2 class="experience-title">Work Experience</h2>
  </div>
  <div class="date-description">
    <div class="dates">
      <div class="button-year-shadow">
        <button class="button-year">2023</button>
      </div>
      <div class="button-year-shadow">
        <button class="button-year">2023</button>
      </div>
      <div class="button-year-shadow">
        <button class="button-year">2022</button>
      </div>
      <div class="button-year-shadow">
        <button class="button-year">2017</button>
      </div>
    </div>
    <div class = "education-description">
      <p class="p-educ"><strong>Full-Stack Engineer path</strong><br>Codecademy</p>
      <p class="p-educ"><strong>Fullstack Web Development Bootcamp</strong><br>Le Wagon Bali, Batch #1134</p>
      <p class="p-educ"><strong>Web Design Certification</strong><br>Freecodecamp</p>
      <p><strong>Master of Social Work</strong><br>IRFSS Red Cross France</p>
    </div>

    <div class="dates-experience">
      <div class="date">
        <div class="button-year-shadow">
          <button class="button-year">2023</button>
        </div>
        <div class="button-year-shadow">
          <button class="button-year">2020</button>
        </div>
        <div class="button-year-shadow">
          <button class="button-year">2017</button>
        </div>
      </div>
      <div class="experience-description">
        <p><strong>Full-Stack web developer</strong><br>Freelance</p>
        <p><strong>Travel around Australia</strong>, work as a machinery operator, mining utility and disability support worker</p>
        <p><strong>Social worker asylum seekers and refugees</strong><br>Coallia and The Salvation Army, France</p>
      </div>
    </div>
  </div>


    <%# <div class="education-experience">
      <div class=education">
        <h2 class="education-title">Education</h2>
        <div class="date-education">
          <div class="button-year-shadow">
            <button class="button-year">2023</button>
          </div>
          <p class="p-educ"><strong>Full-Stack Engineer path</strong><br>Codecademy</p>
        </div>
        <div class="date-education">
          <div class="button-year-shadow">
            <button class="button-year">2023</button>
          </div>
          <p class="p-educ"><strong>Fullstack Web Development Bootcamp</strong><br>Le Wagon Bali, Batch #1134</p>
        </div>
        <div class="date-education">
          <div class="button-year-shadow">
            <button class="button-year">2022</button>
          </div>
          <p class="p-educ"><strong>New Responsive Web Design Certification</strong><br>Freecodecamp</p>
        </div>
        <div class="date-education">
          <div class="button-year-shadow">
            <button class="button-year">2017</button>
          </div>
          <p><strong>Master of Social Work</strong><br>IRFSS Red Cross France</p>
        </div>
      </div>
      <div class="experience">
        <h2 class="experience-title">Experience</h2>
        <div class="date-experience">
          <div class="button-year-shadow">
            <button class="button-year">2023</button>
          </div>
          <p><strong>Full-Stack web developer</strong><br>Freelance</p>
        </div>
        <div class="date-experience">
          <div class="button-year-shadow">
            <button class="button-year">2020</button>
          </div>
          <p>Travel around Australia, work as a machinery operator, mining utility and disability support worker</p>
        </div>
        <div class="date-experience">
          <div class="button-year-shadow">
            <button class="button-year">2017</button>
          </div>
          <p><strong>Social worker asylum seekers and refugees</strong><br>Coallia and The Salvation Army, France</p>
        </div>
       </div>
      </div>
    </div> %>
  </div>

app/views/pages/home.html.erb
<div id="home">
  <div class="text">
    <div class="hello">
      <h1>Hello,</h1>
      <h1>I'm Fanny</h1>
    </div>
      <h2>A Full-Stack Web Developer</h2>
  </div>

  <div class="button-shadow">
    <%= link_to  'Enter', '/about', class: 'button-enter' %>
  </div>
  <div class="icons">
    <a href="mailto:fanny.jousset@gmail.com"><%= image_tag "message.png", class: "message" %></i></a>
    <a href="https://github.com/FnnyJsst"><%= image_tag "github-black.png", class: "github-black" %></i></a>
    <a href="https://www.linkedin.com/in/fanny-jousset/"><%= image_tag "linkedin.png", class: "linkedin" %></i></a>
    <a href="https://www.instagram.com/fnnyjsst/?hl=fr"><%= image_tag "ig.png", class: "insta" %></a>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div id="portfolio">
  <h2>Portfolio</h2>
  <h3>TravelPals</h3>
  <%= image_tag "travelpals.jpg", class: "travelpals" %>
  <div class="buttons">
    <div class="button-code-shadow">
      <a href="https://github.com/FnnyJsst" class="button-code">
        <%= image_tag "github-button.png", class: "github-button" %>
        <span class="button-text">View Code</span>
      </a>
    </div>
    <div class="button-code-shadow">
      <a href="www.travelpals.me" class="button-code">
          <%= image_tag "view.png", class: "view" %>
          <span class="button-text">View Project</span>
      </a>
    </div>
  </div>
  <div class="description-stack">
    <h4>What is it?</h4>
    <p>TravelPals is an app realised in 9 days, designed to help
    solo travelers and digital nomads to meet travel buddies</p>
    <h4>Tech stack</h4>
  </div>
  <div class="stack">
    <%= image_tag "html.png", class: "html-stack" %>
    <%= image_tag "sass.png", class: "sass-stack" %>
    <%= image_tag "js.png", class: "js-stack" %>
    <%= image_tag "rails.png", class: "rails-stack" %>
  </div>
</div>

app/views/pages/skills.html.erb
<div id="skills">
  <h2>Skills</h2>
  <div class="row-skills-1">
    <%= image_tag "html.png", class: "html" %>
    <%= image_tag "css.png", class: "css" %>
    <%= image_tag "sass.png", class: "sass" %>
    <%= image_tag "bootstrap.png", class: "bootstrap" %>
  </div>
  <div class="row-skills-2">
    <%= image_tag "js.png", class: "js" %>
    <%= image_tag "figma.png", class: "figma" %>
    <%= image_tag "ruby.png", class: "ruby" %>
    <%= image_tag "rails.png", class: "rails" %>
  </div>
  <div class="row-skills-3">
    <%= image_tag "git.png", class: "git" %>
    <%= image_tag "github.png", class: "github" %>
    <%= image_tag "postgresql.png", class: "postgresql" %>
    <%= image_tag "mysql.png", class: "mysql" %>
  </div>
</div>